language: node_js
node_js: stable
cache:
  directories:
  - node_modules

before_install:
- git config user.name "erhazhongdeqipa"
- git config user.email "2945330546@qq.com"
- sed -i'' "s~https://github.com/erhazhongdeqipa/erhazhongdeqipa.github.io.git~https://${BlogToken}@github.com/erhazhongdeqipa/erhazhongdeqipa.github.io.git~" _config.yml
install:
- npm install
- npm install hexo-deployer-git --save
script:
- yuque-hexo clean
- yuque-hexo sync
- hexo clean
- npm run sync
- hexo g
- hexo d

branches:
  only:
  - master
env:
  global:
   - GH_REF:  https://github.com/erhazhongdeqipa/erhazhongdeqipa.github.io.git # 就是你github上存放静态博客最终文件的仓库地址末尾加上.git
