language: node_js
node_js: stable
cache:
  directories:
  - node_modules
notifications: 
email:
  recipients:
  - 2945330546@qq.com
  on_success: change
  on_failure: always

before_install:
- export TZ='Asia/Shanghai'
- npm install hexo-cli -g
- chmod +x ./commit-message.sh
install:
- npm install
- npm install hexo-deployer-git --save
script:
- hexo clean
- hexo g 
- hexo d

after_script:
- "./commit-message.sh"
# S: Build Lifecycle
branches:
  only:
  - master
env:
  global:
   - GH_REF: /github.com/erhazhongdeqipa/erhazhongdeqipa.github.io.git # 就是你github上存放静态博客最终文件的仓库地址末尾加上.git
